name: Pruebas unitarias
on:
  push:
    branches: [master]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    seteps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuraci√≥n de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest -v test/test_persona.py
